project:
  name: "ViBT-Style1000"
  root: "/opt/liblibai-models/user-workspace2/users/xqy/project/ViBT"
  output_dir: "outputs/stylization"
  logging_dir: "logs"

model:
  path: "/opt/liblibai-models/user-workspace2/model_zoo/Wan2.1-T2V-1.3B-Diffusers"
  use_lora: true

dataset:
  repo_id: ""
  root: "/opt/liblibai-models/user-workspace2/datasets/style1000_aligned"
  index: "index_for_train.json"
  phase: ""         
  clip_len: 49
  stride: 4            
  height: 480  
  width: 832
  batch_size: 2                                      
  serial_batches: True                             
  num_workers: 16

train:
  lr: 1e-4
  epochs: 20
  gradient_accumulation_steps: 8
  save_interval: 100  # steps
  log_interval: 10     # steps
  mixed_precision: "bf16"
  gradient_checkpointing: True
  instruction: ""
  resume_path: ""

inference:
  num_inference_steps: 28
  noise_scale: 1.0
  shift_gamma: 5.0