project:
  name: "ViBT-Ego2Exo"
  root: "/opt/liblibai-models/user-workspace2/users/xqy/project/ViBT"
  output_dir: "outputs/video2video"
  logging_dir: "logs"

model:
  path: "/opt/liblibai-models/user-workspace2/model_zoo/Wan2.1-T2V-1.3B-Diffusers"
  use_lora: False

dataset:
  repo_id: "Kytolly/examples_Ego2ExoFollowCamera"
  root: "/opt/liblibai-models/user-workspace2/dataset/ego/FollowBench"
  index: "index_clean.json"
  phase: "train"         
  clip_len: 49
  stride: 4            
  height: 480  
  width: 832
  batch_size: 1                                      
  serial_batches: True                             
  num_workers: 16

training:
  lr: 1e-4
  epochs: 20
  gradient_accumulation_steps: 4
  save_interval: 100  # steps
  log_interval: 10     # steps
  mixed_precision: "bf16"
  gradient_checkpointing: True
  instruction: "Transform the view from ego-centric to third-person perspective"
  resume_path: "outputs/video2video/checkpoint_step_100"